name: DataverseLogin
on:
  workflow_dispatch:

jobs:
  login:
    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.DATAVERSEURL }}
        app-id: ${{ secrets.APPID }}
        client-secret: ${{ secrets.CLIENTSECRET }}
        tenant-id: ${{ secrets.TENANTID }}
        cloud: "USGOV"
        
  #reusable_workflow_job:
  #  runs-on: windows-latest
  #  steps:
  #  - uses: actions/msbuild.yml@main
  #    with:
  #      repo-token: ${{ secrets.personal_access_token }}
  #      configuration-path: ${{ inputs.config-path }}


