name: Get Recent Artifact

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  get-recent-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dynamically Get Artifact Info
      - shell: pwsh
        run: |
          $wfId = "13771121330"
          $url = "https://api.github.com/repos/ljrain/DataverseAppInsightsTrackAvailability/actions/workflows/$wfId/runs"
          Write-Host $url
          $runs = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" $url
          Write-Host "$runs"




    # https://github.com/ljrain/DataverseAppInsightsTrackAvailability/actions/runs/13769377136/workflow
    # https://github.com/ljrain/DataverseAppInsightsTrackAvailability/actions/runs/13769377136
    ## 13771121330

    
