# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Track Availability

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:
   build:
    runs-on: windows-lates
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: TrackAvailability
    
