# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Track Availability

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:
   build:
    runs-on: windows-lates
    
    steps:
      - name: Dynamically GetArtifact Info
      - shell: pwsh
      - run: |
         $url = "https://api.github.com/repos/ljrain/DataverseAppInsightsTrackAvailability/actions/workflows"
         Write-Host $url
         $workflows = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" $url
         Write-Host #workflows
