name: Download and Run Tracker

on:
  repository_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
    - name: Dynamically GetArtifact Info
      #if: ${{ inputs.USE_LATEST == 'true' }}
      shell: pwsh
      run: |
          $wfId = "13701502635"
          $url = "https://api.github.com/repos/ljrain/DataverseAppInsightsTrackAvailability/actions/workflows/$wfId/runs"
          Write-Host $url $runs = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" $url
          Write-Host "$runs"
          $runsObj = $runs | ConvertFrom-Json
          Write-Host "$runsObj and $($runsObj.GetType()) and $($runsObj.workflow_runs)"
          #Get the most recent run - GH api defaults list sorted reverse chronologically (index 0)
          $wfRunId = $runsObj.workflow_runs[0].id
          $artifactUrl = $runsObj.workflow_runs[0].artifacts_url
          $artifacts = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" "$artifactUrl"
          $artifactsObj = $artifacts | ConvertFrom-Json
          $artifactName = $artifactsObj.artifacts[0].name
          Write-Host "adding artifact name and wfRun id to env vars $artifactName for run $wfRunId"
          echo "ARTIFACT_NAME=$artifactName" >> $env:GITHUB_ENV
          echo "RUN_ID=$wfRunId" >> $env:GITHUB_ENV    
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
         name: TrackAvailability
         path: ./TrackAvailability-app

    - name: RUnzip artifact
      run: |
        Expand-Archive -Path ./TrackAvailability-app/TrackAvailability.zip -DestinationPath ./TrackAvailability-app

    - name: Run the executable
      run: |
        cd ./TrackAvailability-app
        .\TrackAvailability.exe # Replace with the name of your executable        

