name: Track Availability

on:
   workflow_dispatch:
    inputs:
      USE_LATEST:
        description: "Set to true to use the most recent artificat. (default)"
        required: true
        default: true
   jobs:
      run:
         runs-on: windows-latest
   steps:
   - name: Download a Build Artifact
   uses: actions/download-artifact@v4.1.9
   with:
      # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
      name: # TrackAvailability
      # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
      path: # optional
      # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
      pattern: # optional
      # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
      merge-multiple: # optional, default is false
      # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
      github-token: # optional
      # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
      repository: # optional, default is ${{ github.repository }}
      # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
      run-id: # optional, default is ${{ github.run_id }}
          



    
    - name: Dynamically GetArtifact Info
      #if: ${{ inputs.USE_LATEST == 'true' }}
      shell: pwsh
      run: |
          $wfId = "13701502635"
          $url = "https://api.github.com/repos/ljrain/DataverseAppInsightsTrackAvailability/actions/workflows/$wfId/runs"
          Write-Host $url $runs = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" $url
          Write-Host "$runs"
          echo $runs

          $runsObj = $runs | ConvertFrom-Json
          Write-Host "$runsObj and $($runsObj.GetType()) and $($runsObj.workflow_runs)"
          
          #Get the most recent run - GH api defaults list sorted reverse chronologically (index 0)
          $wfRunId = $runsObj.workflow_runs[0].id
          $artifactUrl = $runsObj.workflow_runs[0].artifacts_url
          $artifacts = curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" "$artifactUrl"
          $artifactsObj = $artifacts | ConvertFrom-Json
          $artifactName = $artifactsObj.artifacts[0].name
          
          Write-Host "adding artifact name and wfRun id to env vars $artifactName for run $wfRunId"
          echo "ARTIFACT_NAME=$artifactName" >> $env:GITHUB_ENV
          echo "RUN_ID=$wfRunId" >> $env:GITHUB_ENV    
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
         name: TrackAvailability
         path: ./TrackAvailability-app

    - name: RUnzip artifact
      run: |
        Expand-Archive -Path ./TrackAvailability-app/TrackAvailability.zip -DestinationPath ./TrackAvailability-app

    - name: Run the executable
      run: |
        cd ./TrackAvailability-app
        .\TrackAvailability.exe # Replace with the name of your executable        

